title: tqdm
google_analytics: 
show_downloads: true
theme: jekyll-theme-dinky

gems:
  - jekyll-mentions

lang: en-GB
github:
  zip_url: https://github.com/tqdm/tqdm/zipball/master
  tar_url: https://github.com/tqdm/tqdm/tarball/master
  repository_url: https://github.com/tqdm/tqdm
  is_user_page: false
  is_project_page: true
  edit_url: https://github.com/tqdm/tqdm.github.io/edit/master/index.md
